# Generated by Django 5.2 on 2025-04-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesertaLomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('waktu_daftar', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
