# Generated by Django 5.1.6 on 2025-04-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member1', 'Member 1'), ('member2', 'Member 2')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=10)),
                ('student_id_card', models.FileField(upload_to='id_cards/')),
                ('proof_mention', models.FileField(upload_to='proof_mentions/')),
                ('registration_post', models.FileField(upload_to='reg_posts/')),
                ('proof_following', models.FileField(upload_to='following/')),
                ('proof_posting', models.FileField(blank=True, null=True, upload_to='postings/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PesertaLomba',
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.team'),
        ),
    ]
